<a href="https://colab.research.google.com/github/pb7141850-web/ml-journey/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - numerical python

Advantages of numpy arrays:
1. allows several mathematics operations
2. faster operations


In [3]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time


Time taken by a list


In [9]:
python_list = [i for i in range(100000)]

start_time= process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.010060587999999981


In [10]:
np_array=np.array([i for i in range(100000)])

start_time= process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)


0.00043620900000007623


Numpy Arrays

In [11]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [12]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [13]:
#create a 2 dim array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [14]:
a.shape

(5,)

In [18]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)


[[1 2 3 4]
 [5 6 7 8]]


In [16]:
b.shape

(2, 4)

In [19]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in Numpy Arrays

In [20]:
#create a numpy arrays of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
# create a numpy array of ones
y=np.ones((3,3,))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# create a array of particular value
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [23]:
#create a identity matrics
a= np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
#create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.11000625 0.85239431 0.69137074 0.0327176 ]
 [0.35842639 0.84792391 0.00382308 0.72463923]
 [0.12922021 0.97360655 0.01609561 0.02230443]]


In [26]:
# ramdon integer values array with specific range

c= np.random.randint(10,100,(3,4))
print(c)

[[89 36 32 53]
 [81 14 33 40]
 [84 72 72 97]]


In [27]:
# array of evenly spaced values --> specifying the number of values required
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [28]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [29]:
#convert a list to numpy array
list2=[10,20,30,40,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [30]:
c= np.random.randint(10,90,(5,5))
print(c)

[[38 27 44 88 54]
 [16 55 34 12 89]
 [52 84 34 43 11]
 [42 59 77 80 47]
 [65 69 71 40 63]]


In [31]:
# array dimension
print(c.shape)

(5, 5)


In [32]:
# number of dimension
print(c.ndim)

2


In [33]:
# check number of elements in a array
print(c.size)

25


In [35]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [1]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1+list2)   # concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
a = np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[5 4 9]
 [5 8 0]
 [7 9 7]]
[[14 13 19]
 [18 18 10]
 [11 11 19]]


In [6]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[19 17 28]
 [23 26 10]
 [18 20 26]]
[[ -9  -9 -10]
 [-13 -10 -10]
 [ -4  -2 -12]]
[[ 70  52 171]
 [ 90 144   0]
 [ 77  99 133]]
[[0.35714286 0.30769231 0.47368421]
 [0.27777778 0.44444444 0.        ]
 [0.63636364 0.81818182 0.36842105]]


In [7]:
a = np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

In [8]:
print(a)
print(b)

[[2 7 7]
 [6 8 4]
 [9 5 8]]
[[16 18 13]
 [10 14 17]
 [13 15 17]]


In [9]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[18 25 20]
 [16 22 21]
 [22 20 25]]
[[-14 -11  -6]
 [ -4  -6 -13]
 [ -4 -10  -9]]
[[ 32 126  91]
 [ 60 112  68]
 [117  75 136]]
[[0.125      0.38888889 0.53846154]
 [0.6        0.57142857 0.23529412]
 [0.69230769 0.33333333 0.47058824]]


Array Manipulation

In [10]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 7 5]
 [6 2 9]]
(2, 3)


In [11]:
# transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[0 6]
 [7 2]
 [5 9]]
(3, 2)


In [12]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 8 7]
 [1 2 7]]
(2, 3)


In [13]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[7 1]
 [8 2]
 [7 7]]
(3, 2)


In [14]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 6 9]
 [0 1 5]]
(2, 3)


In [16]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[9 6]
 [9 0]
 [1 5]]
(3, 2)
